### ISSUE TITLE
fuck off and stop commenting here retard

### ISSUE THREAD

**Issue by Erchobg** [GalaxywareForRoblox/Nebulaware#1]
Hello i would like to talk with you in dms on discord. Please add me erchobg#0000

**Comment by GalaxywareForRoblox** [comment]
Hello I have just seen this

**Comment by GalaxyGuardDev** [comment]
hello

**Comment by GalaxyGuardDev** [comment]
> Hello i would like to talk with you in dms on discord. Please add me erchobg#0000

hi

**Comment by GalaxyGuardDev** [comment]
fuck you

**Comment by GalaxywareForRoblox** [comment]
> Hello i would like to talk with you in dms on discord. Please add me erchobg#0000

hello erco :)

**Comment by Erchobg** [comment]
Can u fuck off

**Comment by GalaxywareForRoblox** [comment]
No lol
